"""Remove unique constraint on teams.name

Revision ID: 37ecebb1ec65
Revises: e606b60e5590
Create Date: 2025-10-18 19:55:43.245974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ecebb1ec65'
down_revision: Union[str, Sequence[str], None] = 'e606b60e5590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_teams_name', table_name='teams')
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.alter_column('teams', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
