"""Add team, prompt, asset models and subteam support

Revision ID: 5fff5a0e7884
Revises: 58ad70f79b91
Create Date: 2025-10-18 11:17:55.320687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fff5a0e7884'
down_revision: Union[str, Sequence[str], None] = '58ad70f79b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
