"""add created_teams relation

Revision ID: 67f31b5dfa7a
Revises: 5fff5a0e7884
Create Date: 2025-10-18 16:01:22.293184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f31b5dfa7a'
down_revision: Union[str, Sequence[str], None] = '5fff5a0e7884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
